export type DietType = "normal" | "vegetarian" | "vegan" | "keto";
export type MealType = "breakfast" | "lunch" | "dinner" | "snack";
export type AllergenType = "gluten" | "dairy" | "egg" | "seafood" | "peanut" | "soy" | "none";

export interface Ingredient {
  name: string;
  quantity: string;
  priceEstimate: number;
}

export interface Meal {
  id: string;
  name: string;
  diet: DietType;
  mealType: MealType;
  price: number;
  calories: number;
  protein: "low" | "medium" | "high";
  protein_g: number;
  carbs_g: number;
  fat_g: number;
  allergens: AllergenType[];
  ingredients: Ingredient[];
  preparation: string;
}

export const meals: Meal[] = [
  // NORMAL - Breakfast
  { id:"n_b1", name:"Akara and Pap", diet:"normal", mealType:"breakfast", price:500, calories:320, protein:"medium", protein_g:14, carbs_g:42, fat_g:10, allergens:["gluten","egg"], ingredients:[{name:"Black-eyed beans",quantity:"1 cup",priceEstimate:200},{name:"Onion",quantity:"1 small",priceEstimate:50},{name:"Pepper",quantity:"2 pieces",priceEstimate:30},{name:"Corn pap",quantity:"1 bowl",priceEstimate:150},{name:"Palm oil",quantity:"1 tbsp",priceEstimate:50},{name:"Salt",quantity:"to taste",priceEstimate:20}], preparation:"Blend beans with onion and pepper. Fry in hot oil until golden. Serve with warm pap." },
  { id:"n_b2", name:"Bread and Egg Sauce", diet:"normal", mealType:"breakfast", price:600, calories:400, protein:"medium", protein_g:16, carbs_g:50, fat_g:14, allergens:["gluten","egg"], ingredients:[{name:"Agege bread",quantity:"4 slices",priceEstimate:200},{name:"Eggs",quantity:"2 large",priceEstimate:200},{name:"Tomatoes",quantity:"2 medium",priceEstimate:80},{name:"Onion",quantity:"1 small",priceEstimate:50},{name:"Vegetable oil",quantity:"1 tbsp",priceEstimate:50},{name:"Salt & seasoning",quantity:"to taste",priceEstimate:20}], preparation:"Fry onions and tomatoes. Add beaten eggs and stir until cooked. Serve with bread." },
  { id:"n_b3", name:"Fried Plantain and Eggs", diet:"normal", mealType:"breakfast", price:700, calories:450, protein:"medium", protein_g:14, carbs_g:58, fat_g:16, allergens:["egg"], ingredients:[{name:"Ripe plantain",quantity:"1 large",priceEstimate:200},{name:"Eggs",quantity:"2 large",priceEstimate:200},{name:"Vegetable oil",quantity:"2 tbsp",priceEstimate:100},{name:"Salt",quantity:"to taste",priceEstimate:20},{name:"Pepper",quantity:"1 piece",priceEstimate:30}], preparation:"Slice plantain and fry until golden. Fry eggs separately. Serve together." },
  { id:"n_b4", name:"Oatmeal with Milk", diet:"normal", mealType:"breakfast", price:400, calories:350, protein:"low", protein_g:10, carbs_g:55, fat_g:8, allergens:["dairy","gluten"], ingredients:[{name:"Rolled oats",quantity:"1 cup",priceEstimate:150},{name:"Milk",quantity:"200ml",priceEstimate:150},{name:"Sugar",quantity:"1 tbsp",priceEstimate:30},{name:"Banana",quantity:"1 medium",priceEstimate:70}], preparation:"Cook oats in milk for 5 minutes. Sweeten and top with banana." },
  { id:"n_b5", name:"Yam and Egg Stew", diet:"normal", mealType:"breakfast", price:800, calories:500, protein:"medium", protein_g:18, carbs_g:65, fat_g:14, allergens:["egg"], ingredients:[{name:"Yam",quantity:"300g",priceEstimate:300},{name:"Eggs",quantity:"2 large",priceEstimate:200},{name:"Tomatoes",quantity:"2 medium",priceEstimate:80},{name:"Onion",quantity:"1 small",priceEstimate:50},{name:"Palm oil",quantity:"1 tbsp",priceEstimate:50},{name:"Seasoning",quantity:"1 cube",priceEstimate:20}], preparation:"Boil yam until soft. Fry tomato stew and scramble eggs in. Serve over yam." },
  // NORMAL - Lunch
  { id:"n_l1", name:"Jollof Rice with Chicken", diet:"normal", mealType:"lunch", price:1500, calories:650, protein:"high", protein_g:38, carbs_g:75, fat_g:18, allergens:["none"], ingredients:[{name:"Long grain rice",quantity:"2 cups",priceEstimate:400},{name:"Chicken",quantity:"2 pieces",priceEstimate:600},{name:"Tomatoes & peppers",quantity:"4 medium",priceEstimate:150},{name:"Onion",quantity:"1 large",priceEstimate:80},{name:"Vegetable oil",quantity:"3 tbsp",priceEstimate:100},{name:"Seasoning & spices",quantity:"to taste",priceEstimate:70}], preparation:"Blend tomatoes and peppers. Fry with onions and oil. Add parboiled rice and cook until done. Grill chicken separately." },
  { id:"n_l2", name:"Fried Rice with Turkey", diet:"normal", mealType:"lunch", price:1800, calories:700, protein:"high", protein_g:42, carbs_g:78, fat_g:20, allergens:["soy"], ingredients:[{name:"Long grain rice",quantity:"2 cups",priceEstimate:400},{name:"Turkey",quantity:"2 pieces",priceEstimate:700},{name:"Mixed vegetables",quantity:"1 cup",priceEstimate:200},{name:"Soy sauce",quantity:"2 tbsp",priceEstimate:100},{name:"Onion & garlic",quantity:"1 each",priceEstimate:100},{name:"Vegetable oil",quantity:"3 tbsp",priceEstimate:100}], preparation:"Parboil rice. Stir fry vegetables and rice with soy sauce. Season turkey and roast separately." },
  { id:"n_l3", name:"Pounded Yam and Egusi Soup", diet:"normal", mealType:"lunch", price:1600, calories:800, protein:"high", protein_g:35, carbs_g:90, fat_g:28, allergens:["seafood"], ingredients:[{name:"Yam",quantity:"500g",priceEstimate:400},{name:"Egusi seeds",quantity:"1 cup",priceEstimate:300},{name:"Beef",quantity:"200g",priceEstimate:500},{name:"Stockfish",quantity:"small piece",priceEstimate:150},{name:"Palm oil",quantity:"3 tbsp",priceEstimate:80},{name:"Leafy vegetables",quantity:"1 bunch",priceEstimate:100}], preparation:"Boil and pound yam until smooth. Fry egusi in palm oil, add meat stock and cook soup until done." },
  { id:"n_l4", name:"Rice and Beans with Stew", diet:"normal", mealType:"lunch", price:900, calories:550, protein:"medium", protein_g:22, carbs_g:80, fat_g:12, allergens:["none"], ingredients:[{name:"Rice",quantity:"1 cup",priceEstimate:200},{name:"Beans",quantity:"1/2 cup",priceEstimate:150},{name:"Tomatoes & pepper",quantity:"3 medium",priceEstimate:100},{name:"Palm oil",quantity:"2 tbsp",priceEstimate:60},{name:"Onion",quantity:"1 small",priceEstimate:50},{name:"Seasoning",quantity:"to taste",priceEstimate:40}], preparation:"Cook rice and beans together. Prepare stew with blended tomatoes and palm oil. Serve over rice and beans." },
  { id:"n_l5", name:"Amala and Ewedu with Beef", diet:"normal", mealType:"lunch", price:1400, calories:700, protein:"high", protein_g:36, carbs_g:82, fat_g:20, allergens:["none"], ingredients:[{name:"Yam flour (elubo)",quantity:"2 cups",priceEstimate:300},{name:"Ewedu leaves",quantity:"1 bunch",priceEstimate:100},{name:"Beef",quantity:"200g",priceEstimate:500},{name:"Locust beans",quantity:"1 tbsp",priceEstimate:50},{name:"Palm oil",quantity:"2 tbsp",priceEstimate:60},{name:"Seasoning",quantity:"to taste",priceEstimate:40}], preparation:"Stir yam flour in boiling water until smooth. Blend ewedu and cook with locust beans. Serve with stewed beef." },
  // NORMAL - Dinner
  { id:"n_d1", name:"Spaghetti Bolognese", diet:"normal", mealType:"dinner", price:1200, calories:600, protein:"high", protein_g:32, carbs_g:72, fat_g:16, allergens:["gluten"], ingredients:[{name:"Spaghetti",quantity:"200g",priceEstimate:300},{name:"Minced beef",quantity:"200g",priceEstimate:500},{name:"Tomatoes",quantity:"3 medium",priceEstimate:100},{name:"Onion & garlic",quantity:"1 each",priceEstimate:80},{name:"Vegetable oil",quantity:"2 tbsp",priceEstimate:80},{name:"Seasoning & herbs",quantity:"to taste",priceEstimate:60}], preparation:"Cook spaghetti al dente. Fry minced beef with tomatoes and spices. Combine and serve." },
  { id:"n_d2", name:"Ofada Rice and Ayamase", diet:"normal", mealType:"dinner", price:1500, calories:650, protein:"high", protein_g:35, carbs_g:76, fat_g:22, allergens:["none"], ingredients:[{name:"Ofada rice",quantity:"2 cups",priceEstimate:500},{name:"Green peppers",quantity:"4 medium",priceEstimate:150},{name:"Assorted meats",quantity:"200g",priceEstimate:500},{name:"Palm oil",quantity:"4 tbsp",priceEstimate:100},{name:"Locust beans",quantity:"1 tbsp",priceEstimate:50},{name:"Onion",quantity:"1 large",priceEstimate:80}], preparation:"Cook ofada rice. Bleach palm oil and fry blended green peppers with locust beans and assorted meats." },
  { id:"n_d3", name:"Semolina and Ofe Onugbu", diet:"normal", mealType:"dinner", price:1300, calories:700, protein:"medium", protein_g:28, carbs_g:88, fat_g:20, allergens:["seafood"], ingredients:[{name:"Semolina flour",quantity:"2 cups",priceEstimate:250},{name:"Bitter leaf",quantity:"1 bunch",priceEstimate:100},{name:"Beef & stockfish",quantity:"200g",priceEstimate:500},{name:"Cocoyam paste",quantity:"100g",priceEstimate:150},{name:"Palm oil",quantity:"3 tbsp",priceEstimate:80},{name:"Seasoning",quantity:"to taste",priceEstimate:50}], preparation:"Stir semolina in boiling water. Cook bitter leaf soup with cocoyam paste, palm oil, and meats." },
  { id:"n_d4", name:"Yam Porridge with Fish", diet:"normal", mealType:"dinner", price:1100, calories:580, protein:"high", protein_g:30, carbs_g:70, fat_g:16, allergens:["seafood"], ingredients:[{name:"Yam",quantity:"400g",priceEstimate:350},{name:"Smoked fish",quantity:"1 medium",priceEstimate:300},{name:"Tomatoes & peppers",quantity:"3 medium",priceEstimate:100},{name:"Palm oil",quantity:"2 tbsp",priceEstimate:60},{name:"Onion",quantity:"1 small",priceEstimate:50},{name:"Seasoning",quantity:"to taste",priceEstimate:40}], preparation:"Cook yam in seasoned water with palm oil, tomatoes and fish until yam is soft and sauce thickens." },
  { id:"n_d5", name:"Beans Porridge and Plantain", diet:"normal", mealType:"dinner", price:800, calories:500, protein:"medium", protein_g:20, carbs_g:72, fat_g:12, allergens:["none"], ingredients:[{name:"Honey beans",quantity:"2 cups",priceEstimate:350},{name:"Ripe plantain",quantity:"1 medium",priceEstimate:150},{name:"Palm oil & crayfish",quantity:"2 tbsp",priceEstimate:100},{name:"Pepper & seasoning",quantity:"to taste",priceEstimate:50}], preparation:"Cook beans until soft. Add palm oil, crayfish and seasoning. Fry plantain slices and serve alongside." },
  // VEGETARIAN - Breakfast
  { id:"v_b1", name:"Akara and Ogi", diet:"vegetarian", mealType:"breakfast", price:400, calories:300, protein:"medium", protein_g:12, carbs_g:44, fat_g:8, allergens:["gluten"], ingredients:[{name:"Black-eyed beans",quantity:"1 cup",priceEstimate:200},{name:"Corn pap",quantity:"1 bowl",priceEstimate:100},{name:"Onion & pepper",quantity:"1 each",priceEstimate:60},{name:"Palm oil",quantity:"2 tbsp",priceEstimate:40}], preparation:"Blend beans with onion and pepper. Fry in palm oil. Serve with warm pap." },
  { id:"v_b2", name:"Vegetable Omelette", diet:"vegetarian", mealType:"breakfast", price:600, calories:380, protein:"medium", protein_g:18, carbs_g:20, fat_g:22, allergens:["egg","dairy"], ingredients:[{name:"Eggs",quantity:"3 large",priceEstimate:300},{name:"Bell peppers",quantity:"1 medium",priceEstimate:80},{name:"Onion",quantity:"1 small",priceEstimate:50},{name:"Tomatoes",quantity:"1 medium",priceEstimate:50},{name:"Butter",quantity:"1 tbsp",priceEstimate:80},{name:"Salt & pepper",quantity:"to taste",priceEstimate:20}], preparation:"Beat eggs and season. Cook vegetables in butter then pour in eggs. Fold and serve." },
  { id:"v_b3", name:"Banana Pancakes", diet:"vegetarian", mealType:"breakfast", price:500, calories:350, protein:"low", protein_g:8, carbs_g:60, fat_g:10, allergens:["gluten","egg","dairy"], ingredients:[{name:"Flour",quantity:"1 cup",priceEstimate:100},{name:"Banana",quantity:"2 ripe",priceEstimate:140},{name:"Egg",quantity:"1 large",priceEstimate:100},{name:"Milk",quantity:"100ml",priceEstimate:100},{name:"Sugar",quantity:"1 tbsp",priceEstimate:30},{name:"Butter",quantity:"1 tbsp",priceEstimate:80}], preparation:"Mash bananas with egg and milk. Add flour and mix. Cook pancakes in butter until golden." },
  { id:"v_b4", name:"Moi Moi with Pap", diet:"vegetarian", mealType:"breakfast", price:450, calories:320, protein:"medium", protein_g:14, carbs_g:42, fat_g:10, allergens:["egg"], ingredients:[{name:"Black-eyed beans",quantity:"2 cups",priceEstimate:200},{name:"Eggs",quantity:"2 large",priceEstimate:200},{name:"Bell pepper & onion",quantity:"1 each",priceEstimate:80},{name:"Corn pap",quantity:"1 bowl",priceEstimate:100},{name:"Palm oil",quantity:"2 tbsp",priceEstimate:50}], preparation:"Blend beans smooth. Mix with eggs, peppers and oil. Steam in foil/leaves. Serve with pap." },
  { id:"v_b5", name:"Toast with Peanut Butter", diet:"vegetarian", mealType:"breakfast", price:350, calories:300, protein:"medium", protein_g:10, carbs_g:38, fat_g:14, allergens:["gluten","peanut"], ingredients:[{name:"Bread",quantity:"2 slices",priceEstimate:150},{name:"Peanut butter",quantity:"2 tbsp",priceEstimate:150},{name:"Banana",quantity:"1 small",priceEstimate:70}], preparation:"Toast bread until golden. Spread peanut butter and top with banana slices." },
  // VEGETARIAN - Lunch
  { id:"v_l1", name:"Vegetable Jollof Rice", diet:"vegetarian", mealType:"lunch", price:1000, calories:550, protein:"low", protein_g:12, carbs_g:82, fat_g:14, allergens:["none"], ingredients:[{name:"Long grain rice",quantity:"2 cups",priceEstimate:400},{name:"Mixed vegetables",quantity:"1 cup",priceEstimate:200},{name:"Tomatoes & peppers",quantity:"4 medium",priceEstimate:150},{name:"Onion",quantity:"1 large",priceEstimate:80},{name:"Vegetable oil",quantity:"3 tbsp",priceEstimate:100},{name:"Seasoning",quantity:"to taste",priceEstimate:70}], preparation:"Blend and fry tomatoes with onion and oil. Parboil rice and finish cooking in the tomato base with vegetables." },
  { id:"v_l2", name:"Moi Moi and Fried Plantain", diet:"vegetarian", mealType:"lunch", price:900, calories:500, protein:"medium", protein_g:16, carbs_g:68, fat_g:14, allergens:["egg"], ingredients:[{name:"Black-eyed beans",quantity:"2 cups",priceEstimate:300},{name:"Ripe plantain",quantity:"1 large",priceEstimate:200},{name:"Eggs",quantity:"2 large",priceEstimate:200},{name:"Palm oil & peppers",quantity:"2 tbsp",priceEstimate:100}], preparation:"Blend beans and steam with egg inside. Fry sliced plantain in oil until caramelized." },
  { id:"v_l3", name:"Egusi Soup with Fufu (no meat)", diet:"vegetarian", mealType:"lunch", price:1100, calories:620, protein:"medium", protein_g:20, carbs_g:80, fat_g:24, allergens:["none"], ingredients:[{name:"Egusi seeds",quantity:"1 cup",priceEstimate:300},{name:"Cassava fufu",quantity:"2 wraps",priceEstimate:200},{name:"Spinach",quantity:"1 bunch",priceEstimate:100},{name:"Palm oil",quantity:"3 tbsp",priceEstimate:80},{name:"Crayfish & seasoning",quantity:"to taste",priceEstimate:100}], preparation:"Fry egusi in palm oil, add stock, crayfish and spinach. Serve with cassava fufu." },
  { id:"v_l4", name:"Vegetable Fried Rice", diet:"vegetarian", mealType:"lunch", price:1000, calories:500, protein:"low", protein_g:10, carbs_g:78, fat_g:12, allergens:["soy"], ingredients:[{name:"Long grain rice",quantity:"2 cups",priceEstimate:400},{name:"Mixed vegetables",quantity:"1 cup",priceEstimate:200},{name:"Soy sauce",quantity:"2 tbsp",priceEstimate:100},{name:"Onion & garlic",quantity:"1 each",priceEstimate:80},{name:"Vegetable oil",quantity:"3 tbsp",priceEstimate:100}], preparation:"Parboil rice. Stir fry vegetables with garlic and oil. Combine with rice and soy sauce." },
  { id:"v_l5", name:"Beans and Plantain", diet:"vegetarian", mealType:"lunch", price:800, calories:480, protein:"high", protein_g:22, carbs_g:70, fat_g:10, allergens:["none"], ingredients:[{name:"Brown beans",quantity:"2 cups",priceEstimate:350},{name:"Ripe plantain",quantity:"1 large",priceEstimate:200},{name:"Palm oil & crayfish",quantity:"2 tbsp",priceEstimate:100},{name:"Pepper & seasoning",quantity:"to taste",priceEstimate:50}], preparation:"Cook beans with palm oil and crayfish until soft. Fry plantain slices and serve together." },
  // VEGETARIAN - Dinner
  { id:"v_d1", name:"Vegetable Stir Fry with Rice", diet:"vegetarian", mealType:"dinner", price:900, calories:450, protein:"low", protein_g:10, carbs_g:72, fat_g:12, allergens:["soy"], ingredients:[{name:"Rice",quantity:"2 cups",priceEstimate:400},{name:"Broccoli & carrots",quantity:"1 cup each",priceEstimate:250},{name:"Soy sauce",quantity:"2 tbsp",priceEstimate:100},{name:"Garlic & ginger",quantity:"1 tsp each",priceEstimate:50}], preparation:"Cook rice. Stir fry vegetables with garlic, ginger and soy sauce. Serve over rice." },
  { id:"v_d2", name:"Yam Porridge with Vegetables", diet:"vegetarian", mealType:"dinner", price:800, calories:480, protein:"low", protein_g:8, carbs_g:74, fat_g:14, allergens:["none"], ingredients:[{name:"Yam",quantity:"400g",priceEstimate:350},{name:"Spinach",quantity:"1 bunch",priceEstimate:100},{name:"Tomatoes & peppers",quantity:"2 medium",priceEstimate:80},{name:"Palm oil",quantity:"2 tbsp",priceEstimate:60},{name:"Seasoning",quantity:"to taste",priceEstimate:40}], preparation:"Cook yam in seasoned water with palm oil and tomatoes. Add spinach and simmer until done." },
  { id:"v_d3", name:"Okra Soup with Eba (no meat)", diet:"vegetarian", mealType:"dinner", price:1000, calories:520, protein:"medium", protein_g:14, carbs_g:76, fat_g:18, allergens:["none"], ingredients:[{name:"Garri",quantity:"2 cups",priceEstimate:150},{name:"Okra",quantity:"10 pieces",priceEstimate:150},{name:"Palm oil",quantity:"2 tbsp",priceEstimate:60},{name:"Crayfish & seasoning",quantity:"to taste",priceEstimate:100},{name:"Periwinkle",quantity:"100g",priceEstimate:200}], preparation:"Pour boiling water over garri and stir into eba. Cook okra soup with palm oil and crayfish." },
  { id:"v_d4", name:"Abacha and Ugba", diet:"vegetarian", mealType:"dinner", price:700, calories:400, protein:"low", protein_g:8, carbs_g:58, fat_g:16, allergens:["none"], ingredients:[{name:"Abacha",quantity:"2 cups",priceEstimate:200},{name:"Ugba (oil bean)",quantity:"100g",priceEstimate:200},{name:"Palm oil",quantity:"3 tbsp",priceEstimate:80},{name:"Crayfish & utazi leaf",quantity:"to taste",priceEstimate:100}], preparation:"Soak abacha. Mix with ugba, palm oil, crayfish and utazi leaf. Toss and serve." },
  { id:"v_d5", name:"Vegetable Pasta", diet:"vegetarian", mealType:"dinner", price:850, calories:460, protein:"low", protein_g:12, carbs_g:70, fat_g:14, allergens:["gluten"], ingredients:[{name:"Pasta",quantity:"200g",priceEstimate:300},{name:"Mixed vegetables",quantity:"1 cup",priceEstimate:200},{name:"Tomato sauce",quantity:"200ml",priceEstimate:150},{name:"Garlic & onion",quantity:"1 each",priceEstimate:80},{name:"Vegetable oil",quantity:"2 tbsp",priceEstimate:80}], preparation:"Cook pasta. Sauté vegetables with garlic and oil. Add tomato sauce and combine with pasta." },
  // VEGAN - Breakfast
  { id:"vg_b1", name:"Oatmeal with Banana", diet:"vegan", mealType:"breakfast", price:350, calories:300, protein:"low", protein_g:8, carbs_g:56, fat_g:6, allergens:["gluten"], ingredients:[{name:"Rolled oats",quantity:"1 cup",priceEstimate:150},{name:"Water or plant milk",quantity:"200ml",priceEstimate:80},{name:"Banana",quantity:"1 ripe",priceEstimate:70},{name:"Groundnuts",quantity:"2 tbsp",priceEstimate:50}], preparation:"Cook oats in water or plant milk. Top with sliced banana and groundnuts." },
  { id:"vg_b2", name:"Akara (no egg) with Zobo", diet:"vegan", mealType:"breakfast", price:400, calories:280, protein:"medium", protein_g:12, carbs_g:38, fat_g:8, allergens:["none"], ingredients:[{name:"Black-eyed beans",quantity:"1 cup",priceEstimate:200},{name:"Onion & pepper",quantity:"1 each",priceEstimate:60},{name:"Palm oil",quantity:"2 tbsp",priceEstimate:50},{name:"Zobo drink",quantity:"1 glass",priceEstimate:100}], preparation:"Blend beans without egg. Fry in palm oil. Serve with chilled zobo drink." },
  { id:"vg_b3", name:"Fruit Salad with Groundnuts", diet:"vegan", mealType:"breakfast", price:500, calories:320, protein:"low", protein_g:8, carbs_g:50, fat_g:10, allergens:["peanut"], ingredients:[{name:"Watermelon",quantity:"2 slices",priceEstimate:150},{name:"Banana",quantity:"1 medium",priceEstimate:70},{name:"Pineapple",quantity:"2 slices",priceEstimate:100},{name:"Roasted groundnuts",quantity:"3 tbsp",priceEstimate:100},{name:"Lime juice",quantity:"1 tbsp",priceEstimate:30}], preparation:"Cut fruits into bite-size pieces. Toss with lime juice and top with groundnuts." },
  { id:"vg_b4", name:"Pap with Groundnut", diet:"vegan", mealType:"breakfast", price:300, calories:260, protein:"low", protein_g:6, carbs_g:44, fat_g:8, allergens:["peanut"], ingredients:[{name:"Corn pap",quantity:"1 bowl",priceEstimate:150},{name:"Roasted groundnuts",quantity:"3 tbsp",priceEstimate:100},{name:"Sugar",quantity:"1 tsp",priceEstimate:20}], preparation:"Prepare warm pap with water. Sweeten lightly and serve with groundnuts." },
  { id:"vg_b5", name:"Plantain and Groundnut Porridge", diet:"vegan", mealType:"breakfast", price:450, calories:350, protein:"low", protein_g:8, carbs_g:58, fat_g:12, allergens:["peanut"], ingredients:[{name:"Unripe plantain",quantity:"2 medium",priceEstimate:200},{name:"Groundnut paste",quantity:"3 tbsp",priceEstimate:150},{name:"Onion & pepper",quantity:"1 each",priceEstimate:60},{name:"Palm oil",quantity:"1 tbsp",priceEstimate:40}], preparation:"Boil plantain with palm oil and seasonings. Stir in groundnut paste and simmer." },
  // VEGAN - Lunch
  { id:"vg_l1", name:"Jollof Rice with Mushrooms", diet:"vegan", mealType:"lunch", price:1000, calories:520, protein:"low", protein_g:10, carbs_g:82, fat_g:12, allergens:["none"], ingredients:[{name:"Rice",quantity:"2 cups",priceEstimate:400},{name:"Mushrooms",quantity:"200g",priceEstimate:300},{name:"Tomatoes & peppers",quantity:"4 medium",priceEstimate:150},{name:"Onion",quantity:"1 large",priceEstimate:80},{name:"Vegetable oil",quantity:"3 tbsp",priceEstimate:100}], preparation:"Blend and fry tomatoes with onion. Cook rice in the base. Sauté mushrooms and serve on top." },
  { id:"vg_l2", name:"Beans and Plantain (vegan)", diet:"vegan", mealType:"lunch", price:800, calories:480, protein:"high", protein_g:22, carbs_g:70, fat_g:10, allergens:["none"], ingredients:[{name:"Brown beans",quantity:"2 cups",priceEstimate:350},{name:"Ripe plantain",quantity:"1 large",priceEstimate:200},{name:"Palm oil",quantity:"2 tbsp",priceEstimate:60},{name:"Pepper & seasoning",quantity:"to taste",priceEstimate:50}], preparation:"Cook beans until soft with palm oil. Fry plantain separately and serve together." },
  { id:"vg_l3", name:"Vegetable Soup with Fufu", diet:"vegan", mealType:"lunch", price:900, calories:500, protein:"low", protein_g:8, carbs_g:80, fat_g:14, allergens:["none"], ingredients:[{name:"Cassava fufu",quantity:"2 wraps",priceEstimate:200},{name:"Mixed leafy vegetables",quantity:"2 bunches",priceEstimate:200},{name:"Palm oil",quantity:"3 tbsp",priceEstimate:80},{name:"Crayfish & seasoning",quantity:"to taste",priceEstimate:100}], preparation:"Cook leafy vegetables in palm oil and crayfish broth. Serve with cassava fufu." },
  { id:"vg_l4", name:"Groundnut Soup with Rice", diet:"vegan", mealType:"lunch", price:1100, calories:580, protein:"medium", protein_g:18, carbs_g:78, fat_g:20, allergens:["peanut"], ingredients:[{name:"Rice",quantity:"2 cups",priceEstimate:400},{name:"Groundnut paste",quantity:"4 tbsp",priceEstimate:200},{name:"Tomatoes & pepper",quantity:"3 medium",priceEstimate:100},{name:"Palm oil",quantity:"2 tbsp",priceEstimate:60},{name:"Seasoning",quantity:"to taste",priceEstimate:50}], preparation:"Cook rice. Prepare groundnut soup by simmering paste with tomatoes and palm oil. Serve over rice." },
  { id:"vg_l5", name:"Lentil Stew with Yam", diet:"vegan", mealType:"lunch", price:950, calories:520, protein:"high", protein_g:24, carbs_g:74, fat_g:10, allergens:["none"], ingredients:[{name:"Red lentils",quantity:"1 cup",priceEstimate:250},{name:"Yam",quantity:"300g",priceEstimate:300},{name:"Tomatoes & pepper",quantity:"3 medium",priceEstimate:100},{name:"Onion & garlic",quantity:"1 each",priceEstimate:80},{name:"Vegetable oil",quantity:"2 tbsp",priceEstimate:80}], preparation:"Boil and cube yam. Cook lentils with tomatoes, onion and garlic into a thick stew. Serve together." },
  // VEGAN - Dinner
  { id:"vg_d1", name:"Vegetable Fried Rice (vegan)", diet:"vegan", mealType:"dinner", price:850, calories:440, protein:"low", protein_g:10, carbs_g:72, fat_g:12, allergens:["soy"], ingredients:[{name:"Rice",quantity:"2 cups",priceEstimate:400},{name:"Mixed vegetables",quantity:"1 cup",priceEstimate:200},{name:"Soy sauce",quantity:"2 tbsp",priceEstimate:100},{name:"Onion & garlic",quantity:"1 each",priceEstimate:80}], preparation:"Parboil rice. Stir fry with vegetables, garlic and soy sauce until done." },
  { id:"vg_d2", name:"Efo Riro with Eba (vegan)", diet:"vegan", mealType:"dinner", price:900, calories:480, protein:"low", protein_g:10, carbs_g:74, fat_g:16, allergens:["none"], ingredients:[{name:"Garri",quantity:"2 cups",priceEstimate:150},{name:"Spinach/efo",quantity:"2 bunches",priceEstimate:150},{name:"Palm oil",quantity:"3 tbsp",priceEstimate:80},{name:"Tatashe",quantity:"2 large",priceEstimate:100},{name:"Crayfish & seasoning",quantity:"to taste",priceEstimate:100}], preparation:"Stir garri in boiling water to make eba. Fry blended peppers in palm oil, add spinach and simmer." },
  { id:"vg_d3", name:"Jollof Spaghetti with Veggies", diet:"vegan", mealType:"dinner", price:800, calories:460, protein:"low", protein_g:10, carbs_g:72, fat_g:12, allergens:["gluten"], ingredients:[{name:"Spaghetti",quantity:"200g",priceEstimate:300},{name:"Tomatoes & peppers",quantity:"3 medium",priceEstimate:100},{name:"Mixed vegetables",quantity:"1 cup",priceEstimate:200},{name:"Vegetable oil",quantity:"2 tbsp",priceEstimate:80},{name:"Seasoning",quantity:"to taste",priceEstimate:50}], preparation:"Cook spaghetti. Blend and fry tomatoes with oil, add vegetables and cooked spaghetti. Stir and serve." },
  { id:"vg_d4", name:"Abacha Salad (vegan)", diet:"vegan", mealType:"dinner", price:650, calories:380, protein:"low", protein_g:6, carbs_g:56, fat_g:14, allergens:["none"], ingredients:[{name:"Abacha",quantity:"2 cups",priceEstimate:200},{name:"Palm oil",quantity:"3 tbsp",priceEstimate:80},{name:"Utazi leaves",quantity:"1 handful",priceEstimate:80},{name:"Crayfish & seasoning",quantity:"to taste",priceEstimate:100}], preparation:"Soak abacha. Mix with palm oil, utazi and crayfish. Toss well and serve." },
  { id:"vg_d5", name:"Okra Soup with Eba (vegan)", diet:"vegan", mealType:"dinner", price:750, calories:420, protein:"low", protein_g:8, carbs_g:68, fat_g:14, allergens:["none"], ingredients:[{name:"Garri",quantity:"2 cups",priceEstimate:150},{name:"Okra",quantity:"10 pieces",priceEstimate:150},{name:"Palm oil",quantity:"2 tbsp",priceEstimate:60},{name:"Crayfish & seasoning",quantity:"to taste",priceEstimate:100}], preparation:"Make eba with garri and boiling water. Cook sliced okra in palm oil and crayfish broth." },
  // KETO - Breakfast
  { id:"k_b1", name:"Scrambled Eggs with Avocado", diet:"keto", mealType:"breakfast", price:900, calories:400, protein:"high", protein_g:22, carbs_g:8, fat_g:32, allergens:["egg","dairy"], ingredients:[{name:"Eggs",quantity:"3 large",priceEstimate:300},{name:"Avocado",quantity:"1 medium",priceEstimate:350},{name:"Butter",quantity:"1 tbsp",priceEstimate:100},{name:"Salt & pepper",quantity:"to taste",priceEstimate:20}], preparation:"Scramble eggs in butter over low heat. Slice avocado and serve alongside." },
  { id:"k_b2", name:"Bacon and Eggs", diet:"keto", mealType:"breakfast", price:1200, calories:450, protein:"high", protein_g:28, carbs_g:2, fat_g:36, allergens:["egg"], ingredients:[{name:"Bacon strips",quantity:"4 pieces",priceEstimate:600},{name:"Eggs",quantity:"2 large",priceEstimate:200},{name:"Butter",quantity:"1 tbsp",priceEstimate:100},{name:"Salt & pepper",quantity:"to taste",priceEstimate:20}], preparation:"Fry bacon until crispy. Fry eggs in bacon fat. Serve together." },
  { id:"k_b3", name:"Boiled Eggs with Suya", diet:"keto", mealType:"breakfast", price:1000, calories:380, protein:"high", protein_g:30, carbs_g:4, fat_g:26, allergens:["egg","peanut"], ingredients:[{name:"Eggs",quantity:"3 large",priceEstimate:300},{name:"Beef suya",quantity:"150g",priceEstimate:600},{name:"Suya spice",quantity:"1 tsp",priceEstimate:50}], preparation:"Boil eggs for 8 minutes. Grill beef with suya spice. Serve together." },
  { id:"k_b4", name:"Omelette with Peppers and Onions", diet:"keto", mealType:"breakfast", price:700, calories:350, protein:"high", protein_g:22, carbs_g:6, fat_g:26, allergens:["egg","dairy"], ingredients:[{name:"Eggs",quantity:"3 large",priceEstimate:300},{name:"Bell peppers",quantity:"1 medium",priceEstimate:80},{name:"Onion",quantity:"1 small",priceEstimate:50},{name:"Butter",quantity:"1 tbsp",priceEstimate:100},{name:"Cheese (optional)",quantity:"30g",priceEstimate:150}], preparation:"Beat eggs. Sauté peppers and onion in butter. Pour eggs over vegetables and fold." },
  { id:"k_b5", name:"Smoked Fish with Vegetables", diet:"keto", mealType:"breakfast", price:1100, calories:420, protein:"high", protein_g:36, carbs_g:6, fat_g:28, allergens:["seafood"], ingredients:[{name:"Smoked mackerel",quantity:"1 medium",priceEstimate:500},{name:"Cucumber",quantity:"1 medium",priceEstimate:150},{name:"Tomatoes",quantity:"2 medium",priceEstimate:100},{name:"Avocado",quantity:"1/2",priceEstimate:200},{name:"Lemon juice",quantity:"1 tbsp",priceEstimate:50}], preparation:"Flake smoked fish. Slice vegetables and avocado. Dress with lemon juice and serve." },
  // KETO - Lunch
  { id:"k_l1", name:"Grilled Chicken and Salad", diet:"keto", mealType:"lunch", price:2000, calories:500, protein:"high", protein_g:45, carbs_g:8, fat_g:28, allergens:["none"], ingredients:[{name:"Chicken breast",quantity:"300g",priceEstimate:900},{name:"Mixed salad leaves",quantity:"2 cups",priceEstimate:300},{name:"Cucumber & tomatoes",quantity:"1 each",priceEstimate:200},{name:"Olive oil",quantity:"2 tbsp",priceEstimate:200},{name:"Seasoning & herbs",quantity:"to taste",priceEstimate:80}], preparation:"Season and grill chicken breast until cooked. Toss salad with olive oil. Serve together." },
  { id:"k_l2", name:"Pepper Soup with Goat Meat", diet:"keto", mealType:"lunch", price:2500, calories:450, protein:"high", protein_g:42, carbs_g:6, fat_g:26, allergens:["none"], ingredients:[{name:"Goat meat",quantity:"400g",priceEstimate:1500},{name:"Pepper soup spice",quantity:"2 tbsp",priceEstimate:200},{name:"Uziza leaves",quantity:"1 handful",priceEstimate:100},{name:"Ehuru & utazi",quantity:"to taste",priceEstimate:100},{name:"Seasoning",quantity:"to taste",priceEstimate:80}], preparation:"Boil goat meat with pepper soup spices until tender. Add uziza and simmer." },
  { id:"k_l3", name:"Grilled Fish with Vegetables", diet:"keto", mealType:"lunch", price:2200, calories:480, protein:"high", protein_g:44, carbs_g:8, fat_g:26, allergens:["seafood"], ingredients:[{name:"Tilapia fish",quantity:"1 large",priceEstimate:1000},{name:"Broccoli",quantity:"1 cup",priceEstimate:300},{name:"Bell peppers",quantity:"2 medium",priceEstimate:200},{name:"Olive oil & herbs",quantity:"2 tbsp",priceEstimate:200},{name:"Lemon",quantity:"1",priceEstimate:100}], preparation:"Marinate fish with herbs and lemon. Grill until done. Steam broccoli and roast peppers." },
  { id:"k_l4", name:"Suya with Coleslaw", diet:"keto", mealType:"lunch", price:1800, calories:520, protein:"high", protein_g:40, carbs_g:10, fat_g:32, allergens:["peanut"], ingredients:[{name:"Beef suya",quantity:"300g",priceEstimate:1200},{name:"Cabbage",quantity:"1/4 head",priceEstimate:150},{name:"Carrots",quantity:"1 medium",priceEstimate:80},{name:"Mayonnaise",quantity:"2 tbsp",priceEstimate:150},{name:"Suya spice",quantity:"2 tbsp",priceEstimate:100}], preparation:"Grill beef with suya spice. Shred cabbage and carrots, dress with mayonnaise for coleslaw." },
  { id:"k_l5", name:"Catfish Pepper Soup", diet:"keto", mealType:"lunch", price:2000, calories:430, protein:"high", protein_g:40, carbs_g:6, fat_g:24, allergens:["seafood"], ingredients:[{name:"Catfish",quantity:"500g",priceEstimate:1200},{name:"Pepper soup spice",quantity:"2 tbsp",priceEstimate:200},{name:"Scent leaves",quantity:"1 handful",priceEstimate:80},{name:"Seasoning",quantity:"to taste",priceEstimate:80}], preparation:"Clean catfish. Boil with pepper soup spice and seasoning. Add scent leaves and serve hot." },
  // KETO - Dinner
  { id:"k_d1", name:"Grilled Turkey with Stir-fry Vegetables", diet:"keto", mealType:"dinner", price:2500, calories:550, protein:"high", protein_g:48, carbs_g:10, fat_g:34, allergens:["none"], ingredients:[{name:"Turkey pieces",quantity:"400g",priceEstimate:1500},{name:"Broccoli & zucchini",quantity:"1 cup each",priceEstimate:400},{name:"Garlic & ginger",quantity:"2 tsp each",priceEstimate:80},{name:"Olive oil",quantity:"2 tbsp",priceEstimate:200},{name:"Seasoning",quantity:"to taste",priceEstimate:80}], preparation:"Season and grill turkey. Stir fry vegetables with garlic, ginger and olive oil. Serve together." },
  { id:"k_d2", name:"Baked Tilapia with Salad", diet:"keto", mealType:"dinner", price:2000, calories:480, protein:"high", protein_g:44, carbs_g:6, fat_g:28, allergens:["seafood"], ingredients:[{name:"Tilapia fillet",quantity:"400g",priceEstimate:1200},{name:"Mixed salad leaves",quantity:"2 cups",priceEstimate:300},{name:"Cherry tomatoes",quantity:"10 pieces",priceEstimate:200},{name:"Olive oil & lemon",quantity:"2 tbsp",priceEstimate:200},{name:"Herbs & seasoning",quantity:"to taste",priceEstimate:80}], preparation:"Season tilapia and bake at 180°C for 20 minutes. Toss salad with olive oil and lemon." },
  { id:"k_d3", name:"Ofe Akwu with Chicken (no rice)", diet:"keto", mealType:"dinner", price:1800, calories:500, protein:"high", protein_g:40, carbs_g:8, fat_g:32, allergens:["none"], ingredients:[{name:"Chicken",quantity:"300g",priceEstimate:900},{name:"Palm fruit",quantity:"400g",priceEstimate:400},{name:"Uziza leaves",quantity:"1 handful",priceEstimate:100},{name:"Crayfish",quantity:"2 tbsp",priceEstimate:100},{name:"Seasoning",quantity:"to taste",priceEstimate:80}], preparation:"Extract palm fruit juice. Cook with chicken, crayfish and uziza leaves into a rich sauce." },
  { id:"k_d4", name:"Beef Stir Fry with Vegetables", diet:"keto", mealType:"dinner", price:2200, calories:520, protein:"high", protein_g:44, carbs_g:10, fat_g:32, allergens:["soy"], ingredients:[{name:"Beef strips",quantity:"300g",priceEstimate:1200},{name:"Bell peppers",quantity:"2 medium",priceEstimate:200},{name:"Broccoli",quantity:"1 cup",priceEstimate:300},{name:"Soy sauce",quantity:"2 tbsp",priceEstimate:100},{name:"Garlic & oil",quantity:"2 cloves",priceEstimate:100}], preparation:"Slice beef thin. Stir fry with vegetables and garlic in hot oil. Add soy sauce and serve." },
  { id:"k_d5", name:"Grilled Prawns and Avocado Salad", diet:"keto", mealType:"dinner", price:3000, calories:450, protein:"high", protein_g:38, carbs_g:8, fat_g:30, allergens:["seafood"], ingredients:[{name:"Tiger prawns",quantity:"300g",priceEstimate:1500},{name:"Avocado",quantity:"2 medium",priceEstimate:600},{name:"Mixed salad leaves",quantity:"2 cups",priceEstimate:300},{name:"Lemon & olive oil",quantity:"2 tbsp",priceEstimate:200},{name:"Garlic & seasoning",quantity:"to taste",priceEstimate:100}], preparation:"Grill prawns with garlic and seasoning. Slice avocado. Toss salad and serve together." },

  // ─── NORMAL - Snacks ──────────────────────────────────────────────────────
  { id:"n_s1", name:"Gala Sausage Roll", diet:"normal", mealType:"snack", price:200, calories:180, protein:"low", protein_g:5, carbs_g:22, fat_g:8, allergens:["gluten"], ingredients:[{name:"Gala sausage roll",quantity:"1 piece",priceEstimate:200}], preparation:"Ready to eat. No preparation needed." },
  { id:"n_s2", name:"Puff-puff", diet:"normal", mealType:"snack", price:200, calories:220, protein:"low", protein_g:4, carbs_g:30, fat_g:9, allergens:["gluten","egg"], ingredients:[{name:"Puff-puff",quantity:"5 pieces",priceEstimate:200}], preparation:"Ready to eat from street vendor." },
  { id:"n_s3", name:"Chin-chin", diet:"normal", mealType:"snack", price:150, calories:200, protein:"low", protein_g:3, carbs_g:28, fat_g:8, allergens:["gluten","egg"], ingredients:[{name:"Chin-chin",quantity:"1 small pack",priceEstimate:150}], preparation:"Ready to eat." },
  { id:"n_s4", name:"Roasted Groundnut", diet:"normal", mealType:"snack", price:100, calories:160, protein:"medium", protein_g:7, carbs_g:6, fat_g:13, allergens:["peanut"], ingredients:[{name:"Roasted groundnuts",quantity:"1 wrap",priceEstimate:100}], preparation:"Ready to eat." },
  { id:"n_s5", name:"Plantain Chips", diet:"normal", mealType:"snack", price:200, calories:190, protein:"low", protein_g:2, carbs_g:28, fat_g:8, allergens:["none"], ingredients:[{name:"Plantain chips",quantity:"1 small pack",priceEstimate:200}], preparation:"Ready to eat." },
  { id:"n_s6", name:"Biscuit (Digestive)", diet:"normal", mealType:"snack", price:150, calories:160, protein:"low", protein_g:2, carbs_g:24, fat_g:6, allergens:["gluten","dairy"], ingredients:[{name:"Digestive biscuits",quantity:"4 pieces",priceEstimate:150}], preparation:"Ready to eat." },
  { id:"n_s7", name:"Doughnut", diet:"normal", mealType:"snack", price:300, calories:280, protein:"low", protein_g:4, carbs_g:38, fat_g:12, allergens:["gluten","egg","dairy"], ingredients:[{name:"Doughnut",quantity:"1 piece",priceEstimate:300}], preparation:"Ready to eat." },
  { id:"n_s8", name:"Boiled Corn", diet:"normal", mealType:"snack", price:200, calories:150, protein:"low", protein_g:4, carbs_g:30, fat_g:2, allergens:["none"], ingredients:[{name:"Fresh corn",quantity:"1 cob",priceEstimate:200}], preparation:"Boil corn in salted water for 20 minutes." },

  // ─── VEGETARIAN - Snacks ──────────────────────────────────────────────────
  { id:"v_s1", name:"Banana", diet:"vegetarian", mealType:"snack", price:100, calories:90, protein:"low", protein_g:1, carbs_g:22, fat_g:0, allergens:["none"], ingredients:[{name:"Banana",quantity:"1 large",priceEstimate:100}], preparation:"Ready to eat." },
  { id:"v_s2", name:"Yoghurt", diet:"vegetarian", mealType:"snack", price:300, calories:150, protein:"medium", protein_g:8, carbs_g:18, fat_g:4, allergens:["dairy"], ingredients:[{name:"Plain yoghurt",quantity:"1 cup",priceEstimate:300}], preparation:"Ready to eat. Add honey if desired." },
  { id:"v_s3", name:"Boiled Groundnut", diet:"vegetarian", mealType:"snack", price:150, calories:180, protein:"medium", protein_g:8, carbs_g:10, fat_g:12, allergens:["peanut"], ingredients:[{name:"Fresh groundnuts",quantity:"1 wrap",priceEstimate:150}], preparation:"Boil groundnuts in salted water for 30 minutes." },
  { id:"v_s4", name:"Peanut Butter Crackers", diet:"vegetarian", mealType:"snack", price:250, calories:200, protein:"medium", protein_g:6, carbs_g:22, fat_g:10, allergens:["gluten","peanut"], ingredients:[{name:"Crackers",quantity:"4 pieces",priceEstimate:150},{name:"Peanut butter",quantity:"1 tbsp",priceEstimate:100}], preparation:"Spread peanut butter on crackers." },
  { id:"v_s5", name:"Boiled Corn", diet:"vegetarian", mealType:"snack", price:200, calories:150, protein:"low", protein_g:4, carbs_g:30, fat_g:2, allergens:["none"], ingredients:[{name:"Fresh corn",quantity:"1 cob",priceEstimate:200}], preparation:"Boil corn in salted water for 20 minutes." },
  { id:"v_s6", name:"Chin-chin", diet:"vegetarian", mealType:"snack", price:150, calories:200, protein:"low", protein_g:3, carbs_g:28, fat_g:8, allergens:["gluten","egg"], ingredients:[{name:"Chin-chin",quantity:"1 small pack",priceEstimate:150}], preparation:"Ready to eat." },

  // ─── VEGAN - Snacks ───────────────────────────────────────────────────────
  { id:"vg_s1", name:"Roasted Groundnut", diet:"vegan", mealType:"snack", price:100, calories:160, protein:"medium", protein_g:7, carbs_g:6, fat_g:13, allergens:["peanut"], ingredients:[{name:"Roasted groundnuts",quantity:"1 wrap",priceEstimate:100}], preparation:"Ready to eat." },
  { id:"vg_s2", name:"Banana", diet:"vegan", mealType:"snack", price:100, calories:90, protein:"low", protein_g:1, carbs_g:22, fat_g:0, allergens:["none"], ingredients:[{name:"Banana",quantity:"1 large",priceEstimate:100}], preparation:"Ready to eat." },
  { id:"vg_s3", name:"Roasted Plantain", diet:"vegan", mealType:"snack", price:200, calories:170, protein:"low", protein_g:2, carbs_g:38, fat_g:2, allergens:["none"], ingredients:[{name:"Unripe plantain",quantity:"1 medium",priceEstimate:200}], preparation:"Roast plantain directly over flame or in oven until tender." },
  { id:"vg_s4", name:"Coconut Chunks", diet:"vegan", mealType:"snack", price:150, calories:160, protein:"low", protein_g:2, carbs_g:8, fat_g:14, allergens:["none"], ingredients:[{name:"Fresh coconut",quantity:"1/4 piece",priceEstimate:150}], preparation:"Break coconut and cut into chunks. Ready to eat." },
  { id:"vg_s5", name:"Boiled Corn", diet:"vegan", mealType:"snack", price:200, calories:150, protein:"low", protein_g:4, carbs_g:30, fat_g:2, allergens:["none"], ingredients:[{name:"Fresh corn",quantity:"1 cob",priceEstimate:200}], preparation:"Boil corn in salted water for 20 minutes." },
  { id:"vg_s6", name:"Zobo Drink with Groundnut", diet:"vegan", mealType:"snack", price:200, calories:140, protein:"low", protein_g:4, carbs_g:18, fat_g:7, allergens:["peanut"], ingredients:[{name:"Zobo drink",quantity:"1 glass",priceEstimate:100},{name:"Roasted groundnuts",quantity:"1 small wrap",priceEstimate:100}], preparation:"Chill zobo and serve with groundnuts." },

  // ─── KETO - Snacks ────────────────────────────────────────────────────────
  { id:"k_s1", name:"Boiled Eggs", diet:"keto", mealType:"snack", price:200, calories:140, protein:"high", protein_g:12, carbs_g:1, fat_g:10, allergens:["egg"], ingredients:[{name:"Eggs",quantity:"2 large",priceEstimate:200}], preparation:"Boil eggs for 8 minutes. Peel and season with salt." },
  { id:"k_s2", name:"Suya Stick", diet:"keto", mealType:"snack", price:300, calories:180, protein:"high", protein_g:20, carbs_g:2, fat_g:10, allergens:["peanut"], ingredients:[{name:"Beef suya",quantity:"1 stick",priceEstimate:300}], preparation:"Ready to eat from vendor." },
  { id:"k_s3", name:"Cucumber and Groundnut", diet:"keto", mealType:"snack", price:150, calories:120, protein:"medium", protein_g:5, carbs_g:6, fat_g:8, allergens:["peanut"], ingredients:[{name:"Cucumber",quantity:"1/2 medium",priceEstimate:80},{name:"Roasted groundnuts",quantity:"1 small wrap",priceEstimate:70}], preparation:"Slice cucumber. Serve with groundnuts." },
  { id:"k_s4", name:"Roasted Groundnut", diet:"keto", mealType:"snack", price:100, calories:160, protein:"medium", protein_g:7, carbs_g:4, fat_g:13, allergens:["peanut"], ingredients:[{name:"Roasted groundnuts",quantity:"1 wrap",priceEstimate:100}], preparation:"Ready to eat." },
  { id:"k_s5", name:"Smoked Fish Strips", diet:"keto", mealType:"snack", price:400, calories:160, protein:"high", protein_g:24, carbs_g:0, fat_g:7, allergens:["seafood"], ingredients:[{name:"Smoked fish strips",quantity:"100g",priceEstimate:400}], preparation:"Ready to eat. Can be warmed briefly." },
  { id:"k_s6", name:"Avocado Slices", diet:"keto", mealType:"snack", price:350, calories:160, protein:"low", protein_g:2, carbs_g:4, fat_g:14, allergens:["none"], ingredients:[{name:"Avocado",quantity:"1/2 medium",priceEstimate:350}], preparation:"Slice avocado and season with salt and lemon juice." },
];
